services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - '9000:9000'
      - '9443:9443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PATH}:/data
